
###
// Get Random Quotes
GET http://localhost:3000/quotes


###
// Post a Quotes
POST http://localhost:3000/quotes
Content-Type: application/json
Authorization: Bearer secret

{
  "author": "-people",
  "quotes": "Berakit-rakit ke hulu berenang-renang ketepian. Bersakit-sakit dahulu, malah mati kemudian"
}
